[package]
name = "fundsui"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
usdc = { git = "https://github.com/circlefin/stablecoin-sui.git", subdir = "packages/usdc", rev = "master" }

[addresses]
fundsui = "0x0"
platform_address = "0x9b35473dffa8082ac35c164c288e3ac4de08115f26b5885e04650a59f63c9a65"

[dev-dependencies]


[dev-addresses]
# platform_address = "0x9b35473dffa8082ac35c164c288e3ac4de08115f26b5885e04650a59f63c9a65"
